import type { NextPage } from 'next';
import Link from 'next/link';
import Image from 'next/image';
import Head from 'next/head';
import Search from '../../components/search';
import { useAppSelector } from '../../redux/hooks';
import { RootState } from '../../redux/store';
import { ProductType } from '../../interfaces/index';
import filter from '../../features/filter';
import Categories from '../../components/categories';

const Posts: NextPage = () => {
	// TODO Sort product according to btns

	const { filters } = useAppSelector((state: RootState) => state.filters);
	const { products } = useAppSelector((state: RootState) => state.produts);
	const filtered: ProductType[] = filter(products, { filters });

	return (
		<div>
			<Head>
				<title> Sams - Products List </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className='md:grid grid-cols-2'>
				<div>
					<Search />
				</div>
				<div className=' my-12 text-center md:flex hidden  '>
					<p className='text-5xl font-bold  p-5 md:self-center '>
						{' '}
						{`Your search gave  ${filtered.length} items`}{' '}
					</p>
				</div>
			</div>
			<div>
				<Categories />
			</div>
			<div className='mt-12'>
				{filtered.map((item) => {
					return (
						<Link
							href={{
								pathname: `/products/productItem`,
								query: {
									id: item.id,
									title: item.title,
									description: item.description,
									img: item.image,
									price: item.price,
									added: item.added
								},
							}}
							passHref
							key={item.id}
						>
							<a>
								<div className='border-2 my-5 mx-2 rounded shadow-lg p-4 xl:w-5/6 md:mx-auto '>
									<div className='grid grid-cols-2 p-2 mb-3 '>
										<p> {item.category.toUpperCase()} in  {item.city}</p>
										<p className='text-right'> Added:   { item.added} </p>
									</div>
									<div className='flex flex-row '>
										<div className='basis-1/4 text-center md:py-0'>
											<Image
												src={item.image}
												alt='sr'
												width={100}
												height={100}
											/>
										</div>
										<div className='basis-3/4  pl-5 '>
											<p className='text-xl font-thin'>{item.title}</p>
											<p className='text-xl font-thin mt-6'> {item.price} Fdj </p>
										</div>
									</div>
								</div>
							</a>
						</Link>
					);
				})}
			</div>
		</div>
	);
};

export default Posts;
