import React, { useEffect } from 'react';
import type { NextPage, InferGetServerSidePropsType } from 'next';
import Head from 'next/head';
import Search from '../components/search';
import Categories from '../components/categories';
import { useAppDispatch } from '../redux/hooks';
import { getProductsAsync } from '../features/productsSlice';
import clientPromise from '../lib/mongo';

type User = {
	_id: string;
	name: string;
	email: string;
	password: string;
};

function Home({
	users,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
	const dispatch = useAppDispatch();
	useEffect(() => {
		dispatch(getProductsAsync());
	});

	return (
		<div>
			<Head>
				<title> Sams </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className=''>
				<div className='my-9 md:w-4/5 mx-auto'>
					<p className='text-4xl xl:text-6xl font-bold text-center '>
						{`Buy and sell on Djibouti's safest classified ads `}
					</p>
				</div>
				<div className=''>
					<Search />
				</div>
			</div>

			<div className='my-12'>
				<Categories />
			</div>

			<div className='my-9'>
				<p className='font-bold text-4xl my-8 text-center'> Our Services </p>
				<div className='md:flex flex-row '>
					<div className='border-2 shadow-md p-3 my-5 md:my-0  '>
						<p className='font-bold text-xl'> Lorem Ipsum </p>
						<p>
							{' '}
							Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
							cupidatat non proident, sunt in culpa qui officia deserunt mollit
							anim id est laborum.{' '}
						</p>
					</div>
					<div className='border-2 shadow-md  p-3 my-5 md:mx-3 md:my-0'>
						<p className='font-bold text-xl'> Lorem Ipsum </p>
						<p>
							{' '}
							Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
							cupidatat non proident, sunt in culpa qui officia deserunt mollit
							anim id est laborum.{' '}
						</p>
					</div>
					<div className='border-2 shadow-md p-3 my-5 md:my-0'>
						<p className='font-bold text-xl'> Lorem Ipsum </p>
						<p>
							{' '}
							Duis aute irure dolor in reprehenderit in voluptate velit esse
							cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
							cupidatat non proident, sunt in culpa qui officia deserunt mollit
							anim id est laborum.{' '}
						</p>
					</div>
				</div>
			</div>
		</div>
	);
}

export const getServerSideProps = async (context) => {
	const client = await clientPromise;
	const db = client.db('asas');
	let users: User[] = await db.collection('users').find({}).toArray();
	users = JSON.parse(JSON.stringify(users));

	return {
		props: { users },
	};
};

export default Home;
