import { useEffect, useRef, useState } from 'react';
import Image from 'next/image';
import Head from 'next/head';
import type { InferGetServerSidePropsType, NextPage } from 'next';
import styled from 'styled-components';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
	faCircleChevronLeft,
	faCircleChevronRight,
} from '@fortawesome/free-solid-svg-icons';
import Link from 'next/link';

const ImageWrap = styled.span`
	box-sizing: content-box;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	width: '100%';
`;

const Product = ({
	product,
	sellerInfo,
	sameCategorie,
}: InferGetServerSidePropsType<typeof getServerSideProps>) => {
	const { title, description, images, price } = product;
	const [currentSlide, setCurrentSlide] = useState(0);
	const nextSlide = () => {
		let newSlide = currentSlide === images.length - 1 ? 0 : currentSlide + 1;
		setCurrentSlide(newSlide);
	};

	const prevSlide = () => {
		let newSlide = currentSlide === 0 ? images.length - 1 : currentSlide - 1;
		setCurrentSlide(newSlide);
	};
	return (
		<div>
			<Head>
				<title> Sams - {title} </title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div className='md:flex'>
				<div className=' mx-1 mt-1 md:basis-4/6 '>
					<div id='default-carousel' className='relative'>
						<div className='overflow-hidden  relative h-64 rounded-lg sm:h-72  xl:h-80 2xl:h-96'>
							<div className=' duration-700 ease-in-out'>
								{images.map((img, index) => {
									return (
										<div
											key={index}
											className={index === currentSlide ? 'block ' : 'hidden'}
										>
											<Image layout='fill' objectFit='fill' src={img} alt='' />
										</div>
									);
								})}
							</div>
						</div>
						<div className='flex absolute  bottom-3 left-1/2 z-30 space-x-3 -translate-x-1/2'>
							<p className='bg-slate-600 text-white py-1 px-3 rounded'>
								{' '}
								{currentSlide + 1} av {images.length}{' '}
							</p>
						</div>
						<button
							type='button'
							className='flex absolute top-0 left-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none'
							onClick={prevSlide}
						>
							<span className='inline-flex justify-center items-center  '>
								<FontAwesomeIcon
									className='w-6 h-6  sm:w-8 sm:h-8 text-slate-600 '
									icon={faCircleChevronLeft}
								/>
							</span>
						</button>
						<button
							type='button'
							className='flex absolute top-0 right-0 z-30 justify-center items-center px-4 h-full cursor-pointer group focus:outline-none'
							onClick={nextSlide}
						>
							<span className='inline-flex justify-center items-center w-8 h-8  '>
								<FontAwesomeIcon
									className='w-6 h-6  sm:w-8 sm:h-8 text-slate-600'
									icon={faCircleChevronRight}
								/>
							</span>
						</button>
					</div>

					<div className='mt-7'>
						<div className='grid grid-cols-2 '>
							<div>
								<p className='text-2xl  '> {title} </p>
								<p className='my-3 font-bold text-xl '> {price} Fdj </p>
							</div>
							<div className='text-right '>
								<button className='bg-slate-600 text-white p-1 w-16 rounded '>
									{' '}
									SAVE{' '}
								</button>
							</div>
						</div>
						<div className=' my-5 w-full border-b border-gray-300'></div>
						<div className='my-8 lg:flex justify-between '>
							<p className='text-lg '>
								{' '}
								Published by :{' '}
								<span className='font-bold '>{sellerInfo.username}</span>
							</p>
							<p className='w-full'>
								{' '}
								Member since: <span> {sellerInfo.joined} </span>{' '}
							</p>

							<button className='mb-5 bg-slate-600 text-white w-full lg:w-40 rounded p-2'>
								{' '}
								SEND MESSAGE{' '}
							</button>
						</div>
						<div>
							<p className='font-bold text-lg '>
								{' '}
								Description : <br />{' '}
								<span className='font-thin'> {description}</span>{' '}
							</p>
						</div>
					</div>
				</div>

				<div className=' hidden md:block md:basis-2/6 md:ml-3  '>
					<div className='border-2 rounded-lg shadow-lg p-2'>
						<p className='font-bold text-center text-xl'>
							{' '}
							Browse job listings{' '}
						</p>
						<ul className='my-3 divide-y'>
							<li className=''>
								<p className='font-bold'>
									Lagerarbetare till långsiktigt projekt! - Möjlighet till
									resjobb!
								</p>
								<p className='text-slate-500 text-sm '>
									MTX Rekrytering & Bemanning ·{' '}
									<span className='text-cyan-500 font-bold'>
										{' '}
										31 dagar kvar{' '}
									</span>{' '}
								</p>
							</li>
							<li className=''>
								<p className='font-bold'>
									Lagerarbetare till långsiktigt projekt! - Möjlighet till
									resjobb!
								</p>
								<p className='text-slate-500 text-sm '>
									MTX Rekrytering & Bemanning ·{' '}
									<span className='text-cyan-500 font-bold'>
										{' '}
										31 dagar kvar{' '}
									</span>{' '}
								</p>
							</li>
						</ul>
						<button className='bg-slate-500 text-white p-2 w-full rounded-lg'>
							{' '}
							See more{' '}
						</button>
						<p className='text-5xl text-center  '> Sams Job </p>
					</div>
				</div>
			</div>
			<div className='bg-slate-50 mt-12 '>
				<p className='text-2xl p-3 font-bold'> Others also looked at </p>
				<ul className='md:flex  '>
					{sameCategorie.map((item, index) => {
						return (
							<li
								key={index}
								className=' bg-white p-2 shadow-lg rounded-lg border-2 w-11/12 md:mx-3 my-3 mx-auto'
							>
								<Link
									href={{
										pathname: `/productItem/`,
										query: {
											id: item._id,
										},
									}}
									passHref
								>
									<a>
										<div className='relative w-28 h-28 md:w-32 md:h-32  mx-auto '>
											<Image
												src={item.images[0]}
												layout='fill'
												objectFit='fill'
												alt='ds'
											/>
										</div>
										<div className='p-1'>
											<p className='text-slate-600 text-lg'> {item.city} </p>
											<p className='text-xl '> {item.title}</p>
											<p className='font-bold text-lg'> {item.price} </p>
										</div>
									</a>
								</Link>
							</li>
						);
					})}
				</ul>
			</div>
		</div>
	);
};

export const getServerSideProps = async (context) => {
	const { id } = context.query;

	const res = await fetch(`http://localhost:3000/api/products/?id=${id}`);
	const product = await res.json();
	//JSON.parse(JSON.stringify(res));

	// get sellerId name
	const { sellerId, category } = product;
	const seller = await fetch(
		`http://localhost:3000/api/products/?sellerId=${sellerId}`
	);
	const sellerInfo = await seller.json();

	// get products of same categorie

	const productCategorie = await fetch(
		`http://localhost:3000/api/products/?category=${category}`
	);
	const sameCategorie = await productCategorie.json();

	return {
		props: { product, sellerInfo, sameCategorie },
	};
};

export default Product;
